from os import path

configfile: "config/config.yml"

# Classic filter
include: "rules/common.smk"
include: "rules/filter_snps.smk"

if config["paralogs"]:
    include: "rules/paralogs.smk"

# Force chr name matching in paths
wildcard_constraints:
    chr_id = "|".join(get_chr_list(config["fai_path"])),
    prefix = config["final_prefix"],
    sample = "|".join(get_sample_list(config["pop_path"]))


rule all:
    input:
        get_output()
    default_target: True