      ###################
      ### CONFIG FILE ###
      ###################

vcf_path: "/projects/plantlp/test/vcf/zmays.test.vcf.gz"
fai_path: "/projects/plantlp/00_DATA/data/zmays_parviglumis/zmays_parviglumis_PRJNA641889.chr1x2.fai"
bed_path: "/projects/plantlp/test/zmays.callable_all_samples.bed"
final_prefix: "test"
paralogs: True
chunks_count: 10
minQ: 30
minind: 1
mincov: 1
bams_list: "/projects/plantlp/test/zmays.10.bams"
ngsparalog_path: "/projects/plantlp/softwares/ngsParalog/ngsParalog" # make sure it's well compiled
